In [1]:
import pandas as pd
import sklearn as sc
import numpy as np
from sklearn.linear_model import LinearRegression

In [18]:
data_set1 = pd.read_csv("advertising.csv",sep=',')

In [19]:
data_set = data_set1.drop(data_set1.columns[0], axis=1)

In [20]:
data_set

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [21]:
y = data_set.iloc[:,-1:]
y

sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [22]:
A = data_set.iloc[:,:-1]
A

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [23]:
linear = LinearRegression()

In [24]:
linear.fit(A,y)

LinearRegression()

In [26]:
w0 = linear.intercept_
w0

array([2.93888937])

In [30]:
coef=linear.coef_
linear.coef_.shape

(1, 3)

In [46]:
x = np.ones(85)
x = x.reshape((85,1))

In [47]:
x.shape

(85, 1)

In [48]:
coef.shape

(1, 85)

In [49]:
coef.dot(x)

array([[0.20586683]])

In [52]:
y = linear.intercept_ + coef.dot(x)
y

array([[0.97440495]])

In [31]:
coef
#la méthode qui augmente plus les ventes est la Radio
#la méthode de publicité qui n'est pas éfficace est le pub par newspapers

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [33]:
w0

array([2.93888937])